### ISSUE TITLE
Passing variable from pre-script to post-script

### ISSUE THREAD

**Issue by grittyninja** [ngduyquockhanh/JScriptor#4]
Problem:
variable from prescript cannot be accessed on postscript.

Prescript
```
let someVariable = null

if(someVariable === null){
someVariable = "Hello"
}
else {
someVariable
}
```

Postscript
```
if(someVariable === "Hello"){
someVariable = "World"
}
else {
someVariable
}


```
Output from prescript
![image](https://github.com/ngduyquockhanh/JScriptor/assets/11958843/23436f21-8891-408e-b355-8bdbe924fc42)
Output from postscript
![image](https://github.com/ngduyquockhanh/JScriptor/assets/11958843/eeaf47dd-ea9d-4375-a684-4883aa755e65)

**Comment by grittyninja** [comment]
@ngduyquockhanh how to pass variable from pre-script? or any localStorage like alternative on GraalVM?

**Comment by ngduyquockhanh** [comment]
Hello, I just updated the new version
